/**
 * Tool System Types & Interfaces
 *
 * Phase 15 (T073): Core interfaces for the CRO agent tool system.
 * Design: Interface-based tools, ToolExecutor owns validation/timing/errors.
 */

import type { Page } from 'playwright';
import type { ZodSchema } from 'zod';
import type { Logger } from '../../utils/logger.js';
import type { PageState, ToolResult, CROActionName } from '../../models/index.js';

/**
 * Context passed to tool.execute()
 * Contains all dependencies a tool needs to perform its work.
 */
export interface ToolContext {
  /** Validated parameters from LLM */
  params: unknown;
  /** Playwright page instance */
  page: Page;
  /** Current page state snapshot */
  state: PageState;
  /** Scoped logger for this tool execution */
  logger: Logger;
}

/**
 * Tool interface - implement this for each CRO tool
 *
 * Example:
 * ```typescript
 * const analyzeCTAs: Tool = {
 *   name: 'analyze_ctas',
 *   description: 'Analyze CTA buttons for clarity and prominence',
 *   parameters: z.object({ selector: z.string().optional() }),
 *   execute: async (ctx) => { ... }
 * };
 * ```
 */
export interface Tool {
  /** Tool name (must be a valid CROActionName) */
  readonly name: CROActionName;
  /** Human-readable description for LLM system prompt */
  readonly description: string;
  /** Zod schema for parameter validation */
  readonly parameters: ZodSchema;
  /** Execute the tool with validated context */
  execute(context: ToolContext): Promise<ToolResult>;
}

/**
 * LLM-friendly tool definition (JSON Schema, no execute function)
 * Generated by ToolRegistry.getToolDefinitions() for system prompt (FR-037)
 */
export interface ToolDefinitionForLLM {
  name: CROActionName;
  description: string;
  /** JSON Schema representation of parameters */
  parameters: Record<string, unknown>;
}

/**
 * Execution context passed to ToolExecutor.execute()
 * Subset of full context - ToolExecutor adds logger and validated params
 */
export interface ExecutionContext {
  /** Playwright page instance */
  page: Page;
  /** Current page state snapshot */
  state: PageState;
  /** Optional verbose flag for logger */
  verbose?: boolean;
}
