/**
 * Heuristics Types - Phase 18b (T106)
 *
 * Core interfaces for heuristic rule engine.
 */

import type { PageState, CROInsight, BusinessType } from '../models/index.js';

/**
 * Heuristic rule interface
 */
export interface HeuristicRule {
  /** Unique rule ID (H001-H010 format) */
  id: string;
  /** Human-readable rule name */
  name: string;
  /** Description of what this rule checks */
  description: string;
  /** CRO category this rule belongs to */
  category: 'cta' | 'form' | 'trust' | 'value_prop' | 'navigation';
  /** Default severity when rule triggers */
  severity: 'critical' | 'high' | 'medium' | 'low';
  /** Business types this rule applies to (empty = all) */
  businessTypes: BusinessType[];
  /**
   * Check function - returns insight if violation found, null otherwise
   * @param state - Current page state with DOM tree
   * @param businessType - Detected business type
   */
  check: (state: PageState, businessType: BusinessType) => CROInsight | null;
}

/**
 * Result of running heuristics engine
 */
export interface HeuristicResult {
  /** Insights generated by heuristics */
  insights: CROInsight[];
  /** Number of rules executed */
  rulesExecuted: number;
  /** Number of rules that passed (no violations) */
  rulesPassed: number;
  /** Number of rules that found violations */
  rulesFailed: number;
  /** Total execution time in ms */
  executionTimeMs: number;
}

/**
 * Options for heuristic engine run
 */
export interface HeuristicEngineOptions {
  /** Only run rules for these categories */
  categories?: ('cta' | 'form' | 'trust' | 'value_prop' | 'navigation')[];
  /** Only run rules with these IDs */
  ruleIds?: string[];
  /** Skip rules that don't match business type */
  filterByBusinessType?: boolean;
}
